# Generated by cucumber-sinatra. (2015-04-20 10:55:13 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'capybara-webkit'

# Chrome Setup for Selenium
# Capybara.register_driver :chrome do |app|
#   Capybara::Selenium::Driver.new(app, browser: :chrome)
# end
# Capybara.javascript_driver = :chrome

Capybara.javascript_driver = :webkit

Capybara.app = RateMyPothole

class RateMyPotholeWorld

  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers

end

World do
  RateMyPotholeWorld.new
end
