# Generated by cucumber-sinatra. (2015-04-20 10:55:13 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'timecop'
require 'capybara-webkit'
require_relative 'rspec_before_after_helper'

DataMapper.auto_migrate!

# # Chrome Setup for Selenium (Keep for Dan)
# Capybara.register_driver :chrome do |app|
#   Capybara::Selenium::Driver.new(app, browser: :chrome)
# end
# Capybara.javascript_driver = :chrome

Capybara.server do |app, port|
  require 'rack/handler/thin'
  Rack::Handler::Thin.run(app, Port: port)
end

Capybara.register_driver :webkit_allow do |app|
  driver = Capybara::Webkit::Driver.new(app)
  driver.allow_url 'maps.googleapis.com'
  driver
end

Capybara.app = RateMyPothole

Capybara.javascript_driver = :selenium

class RateMyPotholeWorld

  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers

end

World do
  RateMyPotholeWorld.new
end
