# Generated by cucumber-sinatra. (2015-04-20 10:55:13 +0100)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'app/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'capybara-webkit'

DataMapper.auto_upgrade!

# # Chrome Setup for Selenium (Keep for Dan)
# Capybara.register_driver :chrome do |app|
#   Capybara::Selenium::Driver.new(app, browser: :chrome)
# end
# Capybara.javascript_driver = :chrome

Capybara.server do |app, port|
  require 'rack/handler/thin'
  Rack::Handler::Thin.run(app, :Port => port)
end

Capybara.javascript_driver = :webkit

Capybara.app = RateMyPothole

class RateMyPotholeWorld

  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers

end

World do
  RateMyPotholeWorld.new
end
